### ISSUE TITLE
When i have 2 dropdown how to identify which dropdown delegate method call ?

### ISSUE THREAD

**Issue by Piyush-Mind** [giuseppebruno/SwiftDropdown#1]
When i have 2 dropdown how to identify which dropdown delegate method call ?

**Comment by giuseppebruno** [comment]
Hi Piyush-Mind,

I've just released an update that allows to set `identifier` and verify it when an item is selected using `dropdownItemSelected` delegate method.

If you like SwiftDropdown, don't forget to star the repo! ⭐️

Have a nice day!
